"""Add current file keys to User

Revision ID: 9b9014007bff
Revises: 80ffabc77d66
Create Date: 2024-08-08 02:08:37.930383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9014007bff'
down_revision = '80ffabc77d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_support_file_s3_key', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('current_main_file_s3_key', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_main_file_s3_key')
        batch_op.drop_column('current_support_file_s3_key')

    # ### end Alembic commands ###
